backend:
  name: github
  repo: "BrunoSantos751/Linktree" # <-- SUBSTITUA AQUI
  branch: "main"                     # <-- SUBSTITUA AQUI (ou "master")

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Configurações Gerais"
    files:
      - label: "Aparência e SEO"
        name: "general"
        file: "src/content/settings.json"
        format: "json"
        fields:
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "Título do Site", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Cor de Fundo", name: "backgroundColor", widget: "color" }
          - { label: "Cor do Botão em Destaque", name: "highlightColor", widget: "color" }

  - name: "links"
    label: "Links"
    folder: "src/content/links"
    create: true
    slug: "{{title}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Ordem", name: "order", widget: "number", hint: "Use números para ordenar os links (ex: 1, 2, 3...)" }
      - { label: "Título do Botão", name: "title", widget: "string" }
      - { label: "URL do Link", name: "url", widget: "string" }
      - { label: "Link em Destaque?", name: "highlight", widget: "boolean", default: false }