backend:
  name: github
  repo: BrunoSantos751/Linktree
  branch: main

media_folder: "src/assets/images" 
public_folder: "/assets/images"  

collections:
  - name: "settings"
    label: "Configurações Gerais"
    files:
      - label: "Aparência e SEO"
        name: "general"
        file: "src/content/settings.json" 
        format: "json"
        fields:
          - { label: "Avatar", name: "avatar", widget: "image" }
          - { label: "Título do Site", name: "title", widget: "string" }
          - { label: "Descrição (SEO)", name: "description", widget: "string" }
          - { label: "Cor de Fundo", name: "backgroundColor", widget: "color" }
          - { label: "Cor do Botão em Destaque", name: "highlightColor", widget: "color" }

  
  - name: "links"
    label: "Links"
    folder: "src/content/links" 
    create: true 
    slug: "{{title}}" 
    extension: "json"  
    format: "json"     
    fields:
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Ordem", name: "order", widget: "number" }
      - { label: "Título do Botão", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Destaque", name: "highlight", widget: "boolean", default: false }